### ISSUE TITLE
Headless fixes should be applied only for chromium based browsers

### ISSUE THREAD

**Issue by petrpatek** [apify/fingerprint-suite#101]
**Describe the bug**
Headless fixes are now applied to all browsers, even if the browser runs in a headful.

**Expected behavior**
`runHeadlessFixes()` function runs only for headless chromium-based browsers.

**Comment by dekelev** [comment]
Same here. Getting this error in Chrome:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/4444781/202457915-e9112707-f0b6-485f-b9b3-e0143ea24099.png">

**Comment by barjin** [comment]
Thank you for submitting this issue. Should be fixed by now in the latest version of the `fingerprint-suite` tools (@2.1.5). 

Thanks again - and feel free to reopen in case of any problems!
