### ISSUE TITLE
"improved webgl" detected by creepjs

### ISSUE THREAD

**Issue by wireguard-dev** [apify/fingerprint-suite#102]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/110654262/202244682-d219f76c-1594-4774-87f5-c564c0c7327f.png">

**Comment by barjin** [comment]
As I mentioned in the original PR (#100), we are aware of this. As CreepJS is seldom used in production and this fix seems to help against other bot-protection measures, we decided to take this risk. However, we'll be closely monitoring this issue. Please let us know if you find out this change trips any real bot protection service in your pipeline.

Closing for now, feel free to reopen with further questions / info :)
