### ISSUE TITLE
Headless does not pass https://bot.sannysoft.com

### ISSUE THREAD

**Issue by bfwg** [apify/fingerprint-suite#109]
### Which package is this bug report for? If unsure which one to select, leave blank

@crawlee/playwright (PlaywrightCrawler)

### Issue description

The headless mode from `launchPlaywright` doesn't not pass tests on https://bot.sannysoft.com/.

**Expected:** 
<img width="589" alt="image" src="https://user-images.githubusercontent.com/12819525/205190933-0aebf59e-e1bb-47bc-96e7-11bfeb6256a1.png">

**Actual:** 
<img width="871" alt="image" src="https://user-images.githubusercontent.com/12819525/205190989-28a027f7-d3ae-4e93-a6d8-1a071b495668.png">

### Code sample

```TypeScript
import { launchPlaywright, utils } from 'crawlee';

const url = 'https://bot.sannysoft.com/';
// Start a browser
const browser = await launchPlaywright({
    launchOptions: {
        headless: true,
    },
});

// Open new tab in the browser
const page = await browser.newPage();


// Navigate to the URL
await page.goto(url);
await new Promise(r => setTimeout(r, 3000));

// Capture the screenshot
await utils.puppeteer.saveSnapshot(page, { key: 'my-key', saveHtml: false });

await browser.close();
```

### Package version

3.0.0

### Node.js version

v16.15.1

### Operating system

MacOS

### Apify platform

- [ ] Tick me if you encountered this issue on the Apify platform

**Comment by LeMoussel** [comment]
It seems OK with firefox browser.

**Comment by barjin** [comment]
Hi, and thanks for sharing this issue! The `launchPlaywright()` method itself does not do anything to hide the tell-tale signs of the headless browsers. In general, you have two options here:
- Use the `PlaywrightCrawler` class from Crawlee, which handles the fingerprint injection internally and provides you with a simple yet powerful interface for crawling pages (docs [here](https://crawlee.dev/api/next/playwright-crawler/class/PlaywrightCrawler), please check it out :)):
```typescript
const { PlaywrightCrawler } = require('crawlee');

(async () => {
    const crawler = new PlaywrightCrawler({
        async requestHandler({ saveSnapshot }) {
            await saveSnapshot();
        },
    });

    await crawler.run([
        'https://bot.sannysoft.com/',
    ]);
})();

```

- Use bare Playwright and our [fingerprinting library](https://github.com/apify/fingerprint-suite) - also doable, albeit a bit more verbose, useful if you want to do some Playwright magic and manage everything yourself:

```typescript
const { chromium } = require('playwright');
const { FingerprintGenerator } = require('fingerprint-generator');
const { FingerprintInjector }  = require('fingerprint-injector');

(async () => {
    const fingerprintGenerator = new FingerprintGenerator();

    const browserFingerprintWithHeaders = fingerprintGenerator.getFingerprint({
        devices: ['desktop'],
        browsers: ['chrome'],
    });

    const fingerprintInjector = new FingerprintInjector();
    const { fingerprint } = browserFingerprintWithHeaders;

    const browser = await chromium.launch();

    // With certain properties, we need to inject the props into the context initialization
    const context = await browser.newContext({
        userAgent: fingerprint.userAgent,
        locale: fingerprint.navigator.language,
        viewport: fingerprint.screen,
    });
   
    // Attach the rest of the fingerprint
   await fingerprintInjector.attachFingerprintToPlaywright(context, browserFingerprintWithHeaders);

   const page = await context.newPage();
   await page.goto('https://bot.sannysoft.com/');
   await page.screenshot({ path: 'screenshot.png' });
   // ...using the Page instance and BrowserContext as you wish
})();
```
The choice is yours. I will close this issue as `wontfix` now (as there is no real issue), but feel free to ask follow-up questions :)

**Comment by bfwg** [comment]
Thank you for the great response. I was able to get my code working with play-wright firefox. Looks like chrome has trouble bypassing [datadome](https://datadome.co/?utm_device=c&utm_matchtype=e&utm_paidcampaignid=6738406742&utm_term=datadome&utm_campaign=UR_G_S_EN_B_Brand&utm_source=GoogleAds&utm_medium=cpc&utm_content=78835585145&hsa_acc=1502247055&hsa_cam=6738406742&hsa_grp=78835585145&hsa_ad=635877423992&hsa_src=g&hsa_tgt=kwd-305961238489&hsa_kw=datadome&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gclid=Cj0KCQiA4aacBhCUARIsAI55maEQHY2GMJYewC1KhQqm1JuKbGnlnZgFD9ul0z_p6Du-bfXVb-M8Qz0aAlnfEALw_wcB) protection.
