### ISSUE TITLE
Automatic model generation/updates

### ISSUE THREAD

**Issue by petrpatek** [apify/fingerprint-suite#11]
Now @Equidem generates the models on his machine from the collected data. We should do this automatically every month to provide a smooth version release with updated data.

The end game should look like this:
 1. Actor generates the models
 2. Actor creates a PR with the new models
 3. If there are no conflicts, the PR is auto-merged
 4. Beta is released
 5. Latest is released manually after checking that everything worked well - once we gain confidence in the process, we can automate this too.

**Comment by barjin** [comment]
we're doing this a bit different now, but it's done :)
