### ISSUE TITLE
Generate appropriate headers for HTTP/1 and HTTP/2

### ISSUE THREAD

**Issue by szmarczak** [apify/fingerprint-suite#14]
Currently it's generated like this:

https://github.com/apify/got-scraping/blob/b9127634e2a426e3a9ee609207db0ba01d5621a5/src/hooks/browser-headers.ts#L60-L69

so it generates 2 different devices for 2 different protocols. `header-generator` should expose a function that would first pick a device and then generate headers for both protocols (for that specific device).

Also sometimes it generates `connection: close` for HTTP/2 which is invalid.

Because HTTP/2 is mostly used and HTTP/3 is getting more and more popular I think we should consider removing devices that are HTTP/1-only.

**Comment by barjin** [comment]
AFAIC this got fixed by #93 and the natural selection (of the browsers in the wild). 

Closing as solved, feel free to reopen in case of any doubts. Thanks!

**Comment by szmarczak** [comment]
This is unrelated to #93 in any way. Currently `got-scraping` does https://github.com/apify/got-scraping/blob/15744b41a11a97069d232deeccd25d97e597dc6b/src/hooks/browser-headers.ts#L60-L69

Instead `header-generator` should pick a device and generate headers for both HTTP/1 and HTTP/2 **for that same device**.
