### ISSUE TITLE
Headers issue in fingerprint injector 2.1.16

### ISSUE THREAD

**Issue by DaBossCoda** [apify/fingerprint-suite#150]
There's a bug in the latest update of fingerprint injector.

When trying to browse onlyfans using fingerprint injector 2.1.16, the wrong accept headers are being sent in one of the requests (https://onlyfans.com/api2/v2/init) and this prevents the site from loading.

In 2.1.16, the accept header for this request is:

`text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`

Whereas, in the working 2.1.15 version, the accept header is:

`application/json, text/plain, */*`

// It's happening on all of the site's api requests.
// Currently working around this using puppeteer's interceptor to modify/correct the request's accept header.
// Happening on many different types of requests, going to just roll back to 2.1.15

**Comment by barjin** [comment]
Hi and thanks for submitting this issue! 

Indeed, the `2.1.16` release includes a different way of handling HTTP headers in outgoing requests for both Playwright and Puppeteer. While our performance benchmarks didn't find any problems with this, it's absolutely true that it can break certain requests on some servers. 

I'll link a PR in a minute that fixes this issue and will release a fixed `2.1.17` version later in the day. 

Thanks again!
