### ISSUE TITLE
Persistent Fingerprints Using Files

### ISSUE THREAD

**Issue by FanaticFalcon** [apify/fingerprint-suite#153]
Hi,
Searched and also tried to ask on Discord, but didn't get an answer.

I need to save the generated fingerprint to a file such that I could load it back later to the browser.
Is there a way to dump and load the fingerprint to/from a file?

(I'm using Node JS v18.14.0 and Puppeteer v19.7.2)

**Comment by barjin** [comment]
Hi and thanks for submitting this issue!

Our fingerprints (the ones you get by calling `FingerprintGenerator.getFingerprint()` are very simple JS objects. Because of this, you can serialize them simply by calling `JSON.stringify(fingerprint)`. You can then save this string to a file using the standard `fs` library. Similarly, when you read contents of such a file to a string, you can 'hydrate' the fingerprint back by calling `JSON.parse(fileContents)`.

Here is the minimal example of how to make this work
```javascript
const { FingerprintGenerator } = require('fingerprint-generator');

const fg = new FingerprintGenerator();
const fingerprint = fg.generate();

const fingerprintAsAString = JSON.stringify(fingerprint);

// store the stringified fingerprint in a file
fs.writeFileSync('generatedFingerprint.json', fingerprintAsAString);

// load the fingerprint from the file
const loadedFingerprint = JSON.parse(fs.readFileSync('generatedFingerprint.json'));
```

I'll close this issue now, but feel free to ask any additional questions :)

**Comment by Leezj9671** [comment]
So how to use it when using `newInjectedContext`?

**Comment by barjin** [comment]
Thank you @Leezj9671, you actually brought up a feature that has been requested quite many times. Starting with **v2.1.22**, the `newInjectedContext` / `newInjectedPage` helper methods accept a new `fingerprint` option. 

This way, you can pass a pre-generated fingerprint to the injector, see example below (and possibly compare to the basic example in README):

```javascript
const { chromium } = require ('playwright');
const { newInjectedContext } = require ('fingerprint-injector');
const { FingerprintGenerator } = require ('fingerprint-generator');

(async () => {
    const browser = await chromium.launch({ headless: false });

    const fingerprint = await new FingerprintGenerator().getFingerprint({
        devices: ['mobile'],
        operatingSystems: ['ios'],
    });

    const context = await newInjectedContext(
        browser,
        {
            fingerprint, // HERE! you can pass the fingerprint now
            newContextOptions: {
                geolocation: {
                    latitude: 51.50853,
                    longitude: -0.12574,
                }
            },
        }
    );
    
    const page = await context.newPage();

   // ... your code using `page` here
})();
```

Let me know if you have any additional questions. Thanks!

**Comment by Leezj9671** [comment]
@barjin Wow! Your response was very detailed and clear, and I really appreciate you taking the time to explain the problem. :)

**Comment by pixu2019** [comment]
@barjin how to use your code with playwright launchPersistentContext? i tried and it's have error: "TypeError: browser.newContext is not a function". 
replace "const browser = await chromium.launch({ headless: false });" with "const browser = await chromium.launchPersistentContext(userDataDir, { headless: false });"

Thanks

**Comment by barjin** [comment]
@pixu2019 note that necromancing a year-old thread only leads to your question getting lost. This is also not related to the original question. Feel free to create a new issue.

With `launchPersistentContext`, you can use the legacy way of injecting the fingerprints with FingerprintInjector instance. See the example below / TypeScript typings on the classes. 

```typescript
import { FingerprintGenerator } from 'fingerprint-generator';
import { FingerprintInjector } from 'fingerprint-injector';
import { chromium } from 'playwright';

(async () => {
    const persistentContext = await chromium.launchPersistentContext('chromium-data', {
        acceptDownloads: true,
        // add your options here
    });

    const generator = new FingerprintGenerator();
    const injector = new FingerprintInjector();
    await injector.attachFingerprintToPlaywright(persistentContext, generator.getFingerprint());

    const page = await persistentContext.newPage();
    
    await page.goto('https://example.com/');
    //...
})();
```
