### ISSUE TITLE
Problem with UA limitation in fingerprint generation.

### ISSUE THREAD

**Issue by mrfussion** [apify/fingerprint-suite#186]
**Describe the bug**
Hello everyone!
I'm having problems with the UA limitation in fingerprint generation.

On some occasions it returns an incorrect UA from another browser, more specifically these:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 YaBrowser/22.11.0.2500 Yowser/2.5 Safari/537.36`
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.114 YaBrowser/22.9.1.1145 Yowser/2.5 Safari/537.36`

I do this about 10,000 times a day and the number of errors is around 50.
The site that I scrape is delicate and does not allow me to falsify the browser model with which I have errors and complications.

**To Reproduce**
```
const fpGen = new FingerprintGenerator({
    devices: ['desktop'],
    browsers: [{name: 'chrome', minVersion: 100}],
});
```

**Expected behavior**
What I'm trying to do is limit the generation to chrome, minimum version 100 and no other one.

**System information:**
 - OS: Linux Debian 11 bullseye
 - Node.js version 16.20.0

**Comment by barjin** [comment]
Hello and thank you for submitting this issue! Indeed, some lesser-known browsers were getting registered as Chrome, which resulted in returning these inconsistent `user-agent` strings on `Chrome` query. 

The linked PR should solve this in the code - but I'll still have to regenerate the model, which might take longer (eta today-tomorrow).

However again, thanks for submitting this!
