### ISSUE TITLE
Opera User Agent Missing.

### ISSUE THREAD

**Issue by Biswajit96** [apify/fingerprint-suite#205]
i notice that Suite can't generate Opera Useragent. but i only need opera for my bot.

**Comment by barjin** [comment]
Hello, and thanks for submitting this issue @Biswajit96 ! 

The `(header | fingerprint)-generator` packages are trained on real data we collect from the internet traffic. Looking into the latest 30000 records (we usually train our models on), I could find only 113 related to Opera browsers - compare with Firefox, which has a similar market share, but around 900 records in our dataset. Unfortunately, with this little data, we simply cannot train the model to generate good enough Opera fingerprints.

I'll have to close this one as _wontfix_ - but feel free to ask more questions (or suggest your own ideas!)
