### ISSUE TITLE
Invalid filename after Electron build

### ISSUE THREAD

**Issue by Stitch-cc** [apify/fingerprint-suite#212]
**Describe the bug**
When initializing BayesianNetwork in the constructor of the HeaderGenerator class, __dirname is used, but after Electron is built, __dirname does not point to the same thing.

**System information:**
 - OS: win
 - Node.js version 18.16.0
 - Electron: 25.4.0

**Additional context**
![image](https://github.com/apify/fingerprint-suite/assets/28957590/d0bdba6a-f7e2-4a54-8148-6c92a1b30fd0)

**Comment by Stitch-cc** [comment]
fs or original-fs in adm-zip cannot find files from asar.

**Comment by ashokgelal** [comment]
I am running into this same exact issue. @Stitch-cc did you find a solution for this?
