### ISSUE TITLE
Chrome and Firefox seem to be duplicating `navigator` props to `clientInformation` on window

### ISSUE THREAD

**Issue by pocesar** [apify/fingerprint-suite#22]
![image](https://user-images.githubusercontent.com/461084/167216257-7a898d61-7139-47c9-89a7-ba0d40101672.png)
![image](https://user-images.githubusercontent.com/461084/167216287-617bd378-cb74-4679-8677-ba1cb01059fc.png)

**Comment by barjin** [comment]
Thank you for bringing this up!

From what I've found, [`clientInformation`](https://developer.mozilla.org/en-US/docs/Web/API/Window#properties) was an IE global property, providing ~`window.navigator` functionality. In Chrome and Firefox, this is probably backwards compatibility thing.

I haven't really found anything wrong with the way it works with (or without) the `fingerprint-injector`. Can you please elaborate a bit more?

**Comment by petrpatek** [comment]
We might have wrongly classified the collected fingerprint in this case. But as @barjin said, we need more info to know what happened.

**Comment by barjin** [comment]
Closing as `wontfix` as the issue is unclear here and it got kinda stale. Feel free to reopen anytime with extra information :)
