### ISSUE TITLE
Antibot system

### ISSUE THREAD

**Issue by ATISI7** [apify/fingerprint-suite#230]
Hi,
I wanted to know how you obtained the results present in the "performance" section present in the ReadMe, in particular I was interested in knowing the name of the antibot system, and where I could find it.

I would like to use it to test the fingerprints generated.

Thanks in advance and best regards.

**Comment by barjin** [comment]
Hi @ATISI7 ,
the benchmark in the readme file is based on a custom list of Cloudflare-protected pages. All logic is hidden in the[ `test/antibot-services/live-testing/cloudflare.ts`](https://github.com/apify/fingerprint-suite/blob/master/test/antibot-services/live-testing/cloudflare.ts) file. 

I'll close this issue now, but feel free to ask any additional questions. Thanks!
