### ISSUE TITLE
Relaxing the constraints & Strict mode

### ISSUE THREAD

**Issue by barjin** [apify/fingerprint-suite#231]
**Describe the feature**
The `header-/fingeprint-generator` packages can sometimes fail with an error saying `No headers based on this input can be generated. Please relax or change some of the requirements you specified`. 

While this is usually caused by user misuse, it's probably not the best UX. 

Let's add a constraint "relaxation" feature - even if it's not possible to meet the requirements completely, the generator should try to generate a header / fingerprint that's "close enough". This should be based on an ordered list of constraints - not every constraint is as important as the others. On the above mentioned error, the generator should try removing the constraints one by one (from the least important to the most one) and checking whether it can generate a consistent fingerprint.  

The users still should have an option to throw an error on too strict constraints (strict mode), but this should be opt-in.

Closes apify/crawlee#2089

**Comment by teammakdi** [comment]
Great to have!
