### ISSUE TITLE
Nowsecure.nl does not pass

### ISSUE THREAD

**Issue by steinpigs** [apify/fingerprint-suite#235]
Nowsecure.nl does not pass even if using non-headless and I manually checked the cloudflare challenge.

**Comment by steinpigs** [comment]
any update on this?

**Comment by barjin** [comment]
We don't have enough information about the nowsecure.nl project and its internals. We are planning development of fingeprint-suite v2, which will use different (and hopefully ) methods of randomizing the browser fingeprint, but this is still just a plan.

A lot of issues in this repo refer to some fingerprinting benchmarks that don't necessarily reflect real world antibot services. Please, report only cases where you were trying to access (scrape, automate) an actual website (Netflix, Amazon, Google Maps...) and it didn't work. While optimizing the tool for benchmarks might help with real-world usage, it also draws our attention and manpower to artificial problems.

**Comment by steinpigs** [comment]
I used nowsecure.nl as an example. What I mean by my question is this project can be detected by cloudflare challenge.

**Comment by steinpigs** [comment]
And even if you manually solve the challenge yourself, it does not passed.
