### ISSUE TITLE
navigator.userAgentData.getHighEntropyValues() doesn't return the values of base hints

### ISSUE THREAD

**Issue by th-yoo** [apify/fingerprint-suite#241]
**Describe the bug**
Accoridng to [the standard](https://wicg.github.io/ua-client-hints/#getHighEntropyValues) **navigator.userAgentData.getHighEntropyValues()** is supposed to return base hint(brands, mobile, platform) values even if no hint is specified, but it does not.

**To Reproduce**
```js
const result = await page.evaluate(async () => {
	// @ts-ignore
	return await navigator.userAgentData.getHighEntropyValues([]);
});

console.log(result);
```
```js
{}
```

**Expected behavior**
```js
{
  brands: [
    { brand: 'Google Chrome', version: '117' },
    { brand: 'Not;A=Brand', version: '8' },
    { brand: 'Chromium', version: '117' }
  ],
  mobile: false,
  platform: 'Windows'
}
```

**System information:**
 - OS: Windows 10
 - Node.js version: 16.15.0

**Additional context**
Solution:
fingerprint-suite/packages/fingerprint-injector/src/utils.js
```diff
--- utils.js	2023-10-21 15:25:24.196293300 +0900
+++ utils.new.js	2023-10-21 18:55:22.288613900 +0900
@@ -501,7 +501,7 @@
                     await target.apply(ctx, args);
 
                     // If the codec is not in our collected data use
-                    const data = {};
+                    const data = {brands, mobile, platform};
                     hints.forEach((hint) => {
                         data[hint] = highEntropyValues[hint];
                     });
```

**Comment by barjin** [comment]
Thank you @th-yoo for submitting this issue (and for the detailed description :)). I've just linked a PR that closes this issue, I'm expecting to release a new version later this week. 

Cheers!
