### ISSUE TITLE
navigator.mediaDevices maybe nullable

### ISSUE THREAD

**Issue by wilsonssss** [apify/fingerprint-suite#251]
**Describe the bug**
`navigator.mediaDevices.getUserMedia` will crash when insecure-context, eg: 127.0.0.1, about:blank

source code: https://github.com/apify/fingerprint-suite/blob/5bfacd1fb55405c4a7e89bef134e919f20419e2b/packages/fingerprint-injector/src/utils.js#L471

**To Reproduce**

```
await injector.attachFingerprintToPuppeteer(page, fingerprint)
await page.goto('about:blank'）
```
And then you see 

```
[pageerror] Cannot set properties of undefined (setting 'getUserMedia')
```

**Expected behavior**
navigator.mediaDevices should have null check.

**Comment by barjin** [comment]
Thank you @wilsonssss for bringing this up. Indeed, when the `mockWebRTC` feature is on, the injection can partially fail on the issue you are mentioning. The linked PR should fix this issue by null-checking the assignment target before assigning.

Thanks again!
