### ISSUE TITLE
What are all the "fingerprintOptions" options of newInjectedPage() from "fingerprint-injector"

### ISSUE THREAD

**Issue by GilGustavoJ** [apify/fingerprint-suite#266]
Hi.

I'm new using this library. 

I would like to know all options to pass in "fingerprintOptions" when i try to create a new Injected Page with Puppeteer.

Greetings.

**Comment by barjin** [comment]
Hello @GilGustavoJ and thank you for your interest in this project!

The easiest way of figuring out the correct parameters is using TypeScript - this library is fully typed, so once you make the switch, your IDE can show you the type hints with all the optional parameters (and usage comments, which are sometimes very useful!)

If you cannot make the switch for any reason, you can also piece all the options together from the type definitions in the source code ([see here](https://github.com/apify/fingerprint-suite/blob/master/packages/fingerprint-generator/src/fingerprint-generator.ts)).

I'll close this issue now, but feel free to ask additional questions if anything is unclear. Thanks!
