### ISSUE TITLE
No Docs/API reference? 

### ISSUE THREAD

**Issue by Strajk** [apify/fingerprint-suite#269]
Previous version of header-generator had proper docs & api reference in readme
https://github.com/apify/header-generator/tree/master#headergeneratoroptions

**Comment by barjin** [comment]
Thanks for bringing our attention to this, the updated package documentation is now in [header-generator/README.md](https://github.com/apify/fingerprint-suite/blob/master/packages/header-generator/README.md) - and soon on the `npm` page as well (as soon as we release a new version there). 

Thanks again (and sorry for the inconvenience)!

**Comment by Strajk** [comment]
> sorry for the inconvenience
this time i'll forgive you, but I don't forget 🐘
