### ISSUE TITLE
Apify knitting - encrypt request body to mask collected attributes.

### ISSUE THREAD

**Issue by petrpatek** [apify/fingerprint-suite#28]

**Comment by barjin** [comment]
I guess any encryption of this kind would have to happen on the user's device, no? In that case, it would be more of a "security by obscurity" situation (how long do the users want to spend decoding this one weird cryptic request to see what data it contains) - either way, it sounds like overkill to me. Is there any reason we want to hide the names of the collected attributes?

**Comment by petrpatek** [comment]
Yeah, I believe we can close this issue. It is nonsense in our setup. Originally we wanted to make it closed source, so it made a bit more sense.

**Comment by barjin** [comment]
Cool, thanks! Closing as `wontfix` then :)
