### ISSUE TITLE
Why are there userAgent versions exceeding the maximum version

### ISSUE THREAD

**Issue by hisay** [apify/fingerprint-suite#288]
fingerprintGenerator = new FingerprintGenerator({
    devices:   'windows' ,
    browsers: [{name:'chrome',minVersion:124}],
});

the result:
fingerprint {
  screen: {
    availHeight: 1392,
    availWidth: 2560,
    pixelDepth: 24,
    height: 1440,
    width: 2560,
    availTop: 0,
    availLeft: 0,
    colorDepth: 24,
    innerHeight: 0,
    outerHeight: 1392,
    outerWidth: 2560,
    innerWidth: 0,
    screenX: 0,
    pageXOffset: 0,
    pageYOffset: 0,
    devicePixelRatio: 1,
    clientWidth: 0,
    clientHeight: 18,
    hasHDR: false
  },
  navigator: {
    userAgent: '**Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',**
    userAgentData: {
      brands: [Array],
      mobile: false,
      platform: 'Windows',
      architecture: 'x86',
      bitness: '64',
      fullVersionList: [Array],
      model: '',
      platformVersion: '10.0.0',
      uaFullVersion: '125.0.6368.2'
    },
    language: 'en-US',
    languages: [ 'en-US' ],
    platform: 'Win32',
    deviceMemory: 8,
    hardwareConcurrency: 16,
    maxTouchPoints: 0,
    product: 'Gecko',
    productSub: '20030107',
    vendor: 'Google Inc.',
    vendorSub: null,
    doNotTrack: null,
    appCodeName: 'Mozilla',
    appName: 'Netscape',
    appVersion: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
    oscpu: null,
    extraProperties: {
      vendorFlavors: [Array],
      isBluetoothSupported: false,
      globalPrivacyControl: null,
      pdfViewerEnabled: true,
      installedApps: []
    },
    webdriver: false
  },
  audioCodecs: {
    ogg: 'probably',
    mp3: 'probably',
    wav: 'probably',
    m4a: 'maybe',
    aac: 'probably'
  },
  videoCodecs: { ogg: '', h264: 'probably', webm: 'probably' },
  pluginsData: {
    plugins: [ [Object], [Object], [Object], [Object], [Object] ],
    mimeTypes: [
      'Portable Document Format~~application/pdf~~pdf',
      'Portable Document Format~~text/pdf~~pdf'
    ]
  },
  battery: { charging: true, chargingTime: 0, dischargingTime: null, level: 1 },
  videoCard: {
    vendor: 'Google Inc. (AMD)',
    renderer: 'ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001636) Direct3D11 vs_5_0 ps_5_0, D3D11)'
  },
  multimediaDevices: {
    speakers: [ [Object] ],
    micros: [ [Object] ],
    webcams: [ [Object] ]
  },
  fonts: [
    'Agency FB',
    'Calibri',
    'Century',
    'Century Gothic',
    'Franklin Gothic',
    'Haettenschweiler',
    'Lucida Bright',
    'Lucida Sans',
    'MS Outlook',
    'MS Reference Specialty',
    'MS UI Gothic',
    'MT Extra',
    'MYRIAD PRO',
    'Marlett',
    'Minion Pro',
    'Monotype Corsiva',
    'Pristina',
    'Segoe UI Light',
    'SimHei'
  ],
  mockWebRTC: false,
  slim: false
}

**Comment by barjin** [comment]
Your input example works with `minVersion` - the generated fingerprint correctly matches the query. Try using `maxVersion` if you want to set an upper limit on the browser version.

```javascript
fingerprintGenerator = new FingerprintGenerator({
   devices: 'windows' ,
   browsers: [{name:'chrome',minVersion:124}],
});
```
