### ISSUE TITLE
Model Update Failed

### ISSUE THREAD

**Issue by 0xARYA** [apify/fingerprint-suite#334]
### **What’s the Issue?**
- **Error Type**: `TypeError`
- **What It Says**: `Cannot read properties of undefined (reading 'includes')`
- **Where It Happens**:  
  ```typescript
  return (httpVersion === '1' ? http1Values : http2Values)?.['*BROWSER'].includes(browserName) ?? true;
  ```
- **What’s Going Wrong**:  
  The code is trying to access `['*BROWSER']` on `http1Values` or `http2Values`, but one of these is coming up as `undefined`. This throws the error when it tries to use `.includes`.

---

### **How to Reproduce It**
Check out the test causing the problem: `[relaxation] strict mode works with fp-only features` in `test/fingerprint-generator/generation.test.ts`. Run it, and you should hit the same issue.

**Comment by 0xARYA** [comment]
https://github.com/apify/fingerprint-suite/blob/5b5a0cf174e0c1d8e66729c77a66fe4272e58fe3/packages/header-generator/src/header-generator.ts#L234

**Comment by 0xARYA** [comment]
@barjin I can submit a PR to resolve this, just want to ensure that this issue hasn't been picked up internally-- or whether it's been flagged and identified as a potential data corruption issue in which case I would assume a PR would not be well suited to solving this issue.

**Comment by barjin** [comment]
Thank you for noticing this @0xARYA , I investigated the issue and decided to _disable the test_, as the underlying problem is both low severity and low impact. This should resume the automatic model updating in the CI. 

Thanks again!
