### ISSUE TITLE
Plugin fingerprint

### ISSUE THREAD

**Issue by dortonway** [apify/fingerprint-suite#38]
**Describe the feature**
Every time I get new fingerprints, amiunique.org shows the same plugins list. It would be better to have it different for better flying under the radars.

**Comment by barjin** [comment]
Thank you for submitting this issue! This is imho the desired behaviour with the latest (2021 - 2022) browser versions - `navigator.plugins` in those versions shows a [hard-coded array of predefined values](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/plugins).

amiunique says that around 70% of devices has been using this hard-coded value in the past 90 days - so there is probably no point in hiding this, as a majority of (valid) devices presents the same values.

I'm closing this for now, but feel free to reopen the issue if I'm missing something :)
