### ISSUE TITLE
Error: Could not override property: oscpu on [object Navigator]

### ISSUE THREAD

**Issue by dekelev** [apify/fingerprint-suite#58]
**Describe the bug**
I'm getting the following error on page loads in some websites:
`VM277:49 Could not override property: oscpu on [object Navigator]. Reason: Cannot read properties of undefined (reading 'get')`

Related to the following code from utils.js:
```
/**
 * @param instance Instance to override.
 * @param overrideObj New instance values.
 */
// eslint-disable-next-line no-unused-vars
function overrideInstancePrototype(instance, overrideObj) {
  Object.keys(overrideObj).forEach((key) => {
    if (!(overrideObj[key] === null)) {
      try {
        overrideGetterWithProxy(Object.getPrototypeOf(instance), key, makeHandler().getterValue(overrideObj[key]));
      }
      catch (e) {
        console.error(`Could not override property: ${key} on ${instance}. Reason: ${e.message} `);
      }
    }
  });
}
```

**To Reproduce**
Load `https://allpeople.com/`.

**Expected behavior**
No console errors.

**System information:**
 - OS: MacOS
 - Node.js version v16.14.0
 - Puppeteer v15.5.0
 - Latest fingerprint-generator & fingerprint-injector libs

**Comment by barjin** [comment]
Thank you for reporting this issue!

`navigator.oscpu` is a [deprecated Firefox property](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/oscpu) that doesn't exist in any other browser - if the `fingerprint-injector` tries to inject the new value into it in such a browser, it fails.

This is fortunately a handled exception and it only pollutes the console, not causing any extra trouble - only providing some debugging info for us.

I'll close this issue now, but feel free to reopen if you have any additional questions :)

**Comment by dekelev** [comment]
You would think that, but I found out that the console error log is monitored in this website and when submitting the search, it will be blocked by a Captcha page unless I exclude the injection of the `oscpu` property and prevent the error from logging into the console.

**Comment by barjin** [comment]
A-ha, good catch 💡 Let's switch to silent errors then. I'm afk this week, but it should get to npm during the weekend, next week tops. 

Again, thanks for reporting and sorry for the wait!

**Comment by dekelev** [comment]
Awesome, thanks!
