### ISSUE TITLE
Chrome is deprecating user-agent starting with v100

### ISSUE THREAD

**Issue by JaneJeon** [apify/fingerprint-suite#9]
Will it affect this library (or fingerprint-injector or got-scraping, which all rely on injecting the user-agent in some form)?

https://www.chromium.org/updates/ua-reduction/

**Comment by barjin** [comment]
Huh, that took us some time :) This should work automatically as `fingerprint-generator` uses ML models trained on data collected in the real world - and these models are retrained regularly. 

Closing this issue, but as always, feel free to reopen it in case of any questions. Thanks! :)
